### ISSUE TITLE
A13 issues

### ISSUE THREAD

**Issue by cilin1105** [Muirey03/PowerModule#5]
Restart button is not working and ui cache button iam not sure but i think is not workin. Safe mode and respring works fine. Another issue when scroll specifically on lock screen wont show any button just the empty box

**Comment by ghost** [comment]
having same issue in iphone 7plus ios 13.3 and using uncover.
Uicache/Reboot not working and if in lockscreen icons of powermodules wont show up.

**Comment by Muirey03** [comment]
uicache works and the reboot button is a duplicate issue (#2)
